/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as LayoutAboutRouteImport } from './routes/_layout.about'
import { Route as ApiUploadImageRouteImport } from './routes/api.upload.image'
import { Route as LayoutDocsSkillRouteImport } from './routes/_layout.docs.skill'
import { Route as LayoutDocsMcpRouteImport } from './routes/_layout.docs.mcp'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiUploadImageRoute = ApiUploadImageRouteImport.update({
  id: '/api/upload/image',
  path: '/api/upload/image',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutDocsSkillRoute = LayoutDocsSkillRouteImport.update({
  id: '/docs/skill',
  path: '/docs/skill',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocsMcpRoute = LayoutDocsMcpRouteImport.update({
  id: '/docs/mcp',
  path: '/docs/mcp',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/docs': typeof DocsRoute
  '/mcp': typeof McpRoute
  '/about': typeof LayoutAboutRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof LayoutIndexRoute
  '/docs/mcp': typeof LayoutDocsMcpRoute
  '/docs/skill': typeof LayoutDocsSkillRoute
  '/api/upload/image': typeof ApiUploadImageRoute
}
export interface FileRoutesByTo {
  '/docs': typeof DocsRoute
  '/mcp': typeof McpRoute
  '/about': typeof LayoutAboutRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof LayoutIndexRoute
  '/docs/mcp': typeof LayoutDocsMcpRoute
  '/docs/skill': typeof LayoutDocsSkillRoute
  '/api/upload/image': typeof ApiUploadImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/docs': typeof DocsRoute
  '/mcp': typeof McpRoute
  '/_layout/about': typeof LayoutAboutRoute
  '/api/$': typeof ApiSplatRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/docs/mcp': typeof LayoutDocsMcpRoute
  '/_layout/docs/skill': typeof LayoutDocsSkillRoute
  '/api/upload/image': typeof ApiUploadImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/docs'
    | '/mcp'
    | '/about'
    | '/api/$'
    | '/'
    | '/docs/mcp'
    | '/docs/skill'
    | '/api/upload/image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/docs'
    | '/mcp'
    | '/about'
    | '/api/$'
    | '/'
    | '/docs/mcp'
    | '/docs/skill'
    | '/api/upload/image'
  id:
    | '__root__'
    | '/_layout'
    | '/docs'
    | '/mcp'
    | '/_layout/about'
    | '/api/$'
    | '/_layout/'
    | '/_layout/docs/mcp'
    | '/_layout/docs/skill'
    | '/api/upload/image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  DocsRoute: typeof DocsRoute
  McpRoute: typeof McpRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiUploadImageRoute: typeof ApiUploadImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/upload/image': {
      id: '/api/upload/image'
      path: '/api/upload/image'
      fullPath: '/api/upload/image'
      preLoaderRoute: typeof ApiUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/docs/skill': {
      id: '/_layout/docs/skill'
      path: '/docs/skill'
      fullPath: '/docs/skill'
      preLoaderRoute: typeof LayoutDocsSkillRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/docs/mcp': {
      id: '/_layout/docs/mcp'
      path: '/docs/mcp'
      fullPath: '/docs/mcp'
      preLoaderRoute: typeof LayoutDocsMcpRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutDocsMcpRoute: typeof LayoutDocsMcpRoute
  LayoutDocsSkillRoute: typeof LayoutDocsSkillRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutDocsMcpRoute: LayoutDocsMcpRoute,
  LayoutDocsSkillRoute: LayoutDocsSkillRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  DocsRoute: DocsRoute,
  McpRoute: McpRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiUploadImageRoute: ApiUploadImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
